# Ruby environment
FROM ruby:2.4
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev libgconf-2-4

RUN apt-get update && \
    apt-get install -y nodejs \
                       vim \
                       mysql-client \
                       --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app1
WORKDIR /app
# For development we do NOT run bundle here, to avoid rebuilding every time
# we change the Gemfile (which would lead to a full download of every gem in
# the project again)
#
# Our Makefile drives the (re)bundling when necessary. We do not bust Bundler's
# cache (thanks to the bundle_cache container defined on docker-compose.yml)
# and therefore only download new gems.
#
ADD . /app
