version: '2'
services:
  db:
    image: mysql:5.6
    ports:
      - '3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  # the base
  base: &base
    # mem_limit: 2048m
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    volumes_from:
      - bundle_cache
    environment:
      - DOCKER=true
    tty: true
    stdin_open: true

  # the web api
  backend:
    <<: *base
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    privileged: true

  # caching the bundle
  bundle_cache:
    image: ruby:2.4 # Should be the same as the app Dockerfile base image
    volumes:
      - /usr/local/bundle
